// frontend-react/src/components/lightning-talk-detail/lightning-talk-detail.component.js
import React, { useState, useEffect, useContext } from 'react';
import { useParams } from 'react-router-dom';

import './lightning-talk-detail.component.css';
import { useForceUpdate } from '../../utils/force-update';
import LightningTalkService from '../../services/lightning-talk.service';
import AuthService from '../../services/auth.service';
import { UserContext } from '../../contexts/user';

// Use web components with React properties and functions
import reactifyWc from 'reactify-wc';
const XSlideshow = reactifyWc('x-slideshow');


function LightningTalkDetail() {
  // Need the query page index
  const params = useParams();

  const [lightningTalk, setLightningTalk] = useState(null);
  const [updateCounter, forceUpdate] = useForceUpdate();
  const [currentUser] = useContext(UserContext);

  useEffect(() => {
    LightningTalkService.get(params.id).then(res => {
      setLightningTalk(res.data.result);
    });
  }, [updateCounter, params.id, currentUser]);

  const toggleVote = async (item) => {
    if (item.voted) {
      await LightningTalkService.unvote(item.id);
    } else {
      await LightningTalkService.vote(item.id);
    }
    // force UI update to show the new votes
    forceUpdate();
  };

  return (
    lightningTalk &&
      <div className="row">
        <div className="col-12 col-lg-9">
          <div className="row pt-2">
            <div className="col-12">
              { // XSlideshow is a web component to show PPT images,
                // Display a place holder if no images.
                lightningTalk.images && lightningTalk.images.length > 0
                ? <XSlideshow
                    style={{width: '100%'}}
                    images={ lightningTalk.images.map(i => `http://${lightningTalk.store}/upload/${i}`) } />
                : <img
                    style={{width: '100%'}}
                    src="https://via.placeholder.com/800x600.png?text=PPT+is+Still+Processing" className="img-fluid" alt="" />
              }
            </div>
          </div>
          <div className="row pt-4">
            <div className="col-12">
              <div className="px-2">
                <h3>{lightningTalk.title}</h3>
                <div className="row">
                  <div className="col-6">
                    <b>Creator:</b> {lightningTalk.owner.username}
                  </div>
                  <div className="col-6 text-right">
                    { // Non-login user:
                      //   1. Show 'vote' for non-login viewer.
                      // Login user:
                      //   2. Hide the button for user's own talk
                      //   3. Show 'vote' for not-voted item
                      //   4. Show 'unvote' for voted item
                      lightningTalk.owner.username !== AuthService.getCurrentUser()?.username
                      &&  <button
                            className={'btn btn-sm ' + (lightningTalk.voted ? 'btn-primary':'btn-outline-primary')}
                            onClick={() => toggleVote(lightningTalk)}
                            >{lightningTalk.voted ? 'unvote':'vote'}</button>
                    }
                    <span className="pl-2">{lightningTalk.votes} votes</span>
                  </div>
                </div>
                <hr />
                <p>{lightningTalk.description}</p>
              </div>
            </div>
          </div>
        </div>
        <div className="col-12 col-lg-3 bg-light">
          <div className="row py-2">
            <div className="col">
              <img width="100%" src="//via.placeholder.com/150x100" alt="" />
            </div>
          </div>
          <div className="row py-2">
            <div className="col">
              <img width="100%" src="//via.placeholder.com/150x100" alt="" />
            </div>
          </div>
          <div className="row py-2">
            <div className="col">
              <img width="100%" src="//via.placeholder.com/150x100" alt="" />
            </div>
          </div>
          <div className="row py-2">
            <div className="col">
              <img width="100%" src="//via.placeholder.com/150x100" alt="" />
            </div>
          </div>
          <div className="row py-2">
            <div className="col">
              <img width="100%" src="//via.placeholder.com/150x100" alt="" />
            </div>
          </div>
        </div>
      </div>
  );
}

export default LightningTalkDetail;

// frontend/src/app/components/lightning-talk-detail/lightning-talk-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { AuthenticationService } from 'src/app/services/authentication.service';
import { LightningTalkService } from 'src/app/services/lightning-talk.service';

@Component({
  selector: 'app-lightning-talk-detail',
  templateUrl: './lightning-talk-detail.component.html',
  styleUrls: ['./lightning-talk-detail.component.css']
})
export class LightningTalkDetailComponent implements OnInit {
  id;
  item;

  constructor(private route: ActivatedRoute, private lightningTalkService: LightningTalkService, private authService: AuthenticationService) { }

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id');
    this.lightningTalkService.get(this.id).subscribe((data:any) => {
      this.item = data.result;
    })

    // refresh data when current user changed
    this.authService.currentUser.subscribe(() => {
      this.lightningTalkService.get(this.id).subscribe((data: any) => {
        this.item = data.result;
      });
    });
  }

  generatePath(store, imgPath) {
    if (Array.isArray(imgPath)) {
      return imgPath.map(path => `//${store}/upload/${path}`)
    } else {
      return `//${store}/upload/${imgPath}`;
    }
  }

  own(item) {
    const me = this.authService.currentUserValue;
    return me && me.username === item.owner.username;
  }

  vote(item) {
    this.lightningTalkService.vote(item.id).subscribe(() => {
      this.lightningTalkService.get(this.id).subscribe((data: any) => {
        this.item = data.result;
      });
    });
  }

  unvote(item) {
    this.lightningTalkService.unvote(item.id).subscribe(() => {
      this.lightningTalkService.get(this.id).subscribe((data: any) => {
        this.item = data.result;
      });
    });
  }
}

<div *ngIf="item" class="row">
  <div class="col-12 col-lg-9">
    <div class="row pt-2">
      <div class="col-12">
        <x-slideshow *ngIf="(item.images && item.images.length); else noimages" style="width: 100%" [images]="generatePath(item.store, item.images)"></x-slideshow>
        <ng-template #noimages>
          <img style="width: 100%" src="https://via.placeholder.com/800x600.png?text=PPT+is+Still+Processing" class="img-fluid">
        </ng-template>
      </div>
    </div>
    <div class="row pt-4">
      <div class="col-12">
        <div class="px-2">
          <h3>{{item.title}}</h3>
          <div class="row">
            <div class="col-6">
              <b>Creator:</b> {{item.owner.username}}
            </div>
            <div class="col-6 text-right">
              <ng-container *ngIf="!own(item)">
                <button *ngIf="item.voted" class="btn btn-sm btn-primary" (click)="unvote(item)">unvote</button>
                <button *ngIf="!item.voted" class="btn btn-sm btn-outline-primary" (click)="vote(item)">vote</button>
              </ng-container>
              <span class="pl-2">{{item.votes}} votes</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12 col-lg-3 bg-light">
    <div class="row py-2">
      <div class="col">
        <img width="100%" src="//via.placeholder.com/150x100" >
      </div>
    </div>
    <div class="row py-2">
      <div class="col">
        <img width="100%" src="//via.placeholder.com/150x100" >
      </div>
    </div>
    <div class="row py-2">
      <div class="col">
        <img width="100%" src="//via.placeholder.com/150x100" >
      </div>
    </div>
    <div class="row py-2">
      <div class="col">
        <img width="100%" src="//via.placeholder.com/150x100" >
      </div>
    </div>
    <div class="row py-2">
      <div class="col">
        <img width="100%" src="//via.placeholder.com/150x100" >
      </div>
    </div>
  </div>
</div>
