// frontend/src/app/components/create-lightning-talk/create-lightning-talk.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { LightningTalkService } from 'src/app/services/lightning-talk.service';

@Component({
  selector: 'app-create-lightning-talk',
  templateUrl: './create-lightning-talk.component.html',
  styleUrls: ['./create-lightning-talk.component.css']
})
export class CreateLightningTalkComponent implements OnInit {
  apiResult;
  createForm: FormGroup;

  constructor(private formBuilder: FormBuilder, private router: Router, private lightningTalkService: LightningTalkService) { }

  ngOnInit(): void {
    this.createForm = this.formBuilder.group({
      title: ['', Validators.required],
      file: [null, Validators.required],
      fileSource: ['', Validators.required],
    });
  }

  handleFileInput(files: FileList) {
    this.createForm.patchValue({
      fileSource: files.item(0)
    });
  }

  get controls() { return this.createForm.controls; }

  submit() {
    if (!this.createForm.valid) {
      return;
    }

    this.lightningTalkService.create(this.controls.title.value, this.controls.fileSource.value).subscribe((data: any) => {
      this.apiResult = data.error;
      if (!data.error) {
        return this.router.navigate(['lightningtalks', data.result.id]);
      }
    }, (error) => {
      this.apiResult = error;
    });
  }
}

<h1 class="my-4 pt-4">Create Lightning Talk</h1>
<form class="form-group" [formGroup]="createForm" (ngSubmit)="submit()">
  <div class="row">
    <div class="col">
      <label for="title">Title
        <span *ngIf="createForm.controls['title'].invalid" class="text-danger">
          <span *ngIf="createForm.controls['title'].errors.required">*</span>
        </span>
      </label>
      <input id="title" name="title" type="text" formControlName="title" class="form-control">
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <label for="description">Description
        <span *ngIf="createForm.controls['description'].invalid" class="text-danger">
          <span *ngIf="createForm.controls['description'].errors.required">*</span>
        </span>
      </label>
      <textarea id="description" name="description" type="text" formControlName="description" class="form-control"></textarea>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <label for="file">PowerPoint
        <span *ngIf="createForm.controls['file'].invalid" class="text-danger">
          <span *ngIf="createForm.controls['file'].errors.required">*</span>
        </span>
      </label>
      <input id="file" type="file" accept=".ppt,.pptx" name="file" formControlName="file" class="form-control" (change)="handleFileInput($event.target.files)">
    </div>
  </div>
  <div *ngIf="apiResult && apiResult.error" class="row mt-3">
    <div class="col-12 alert alert-warning" role="alert">
      <ul class="mb-0">
        <li *ngFor="let msg of apiResult.message">
          <strong>{{msg}}.</strong>
        </li>
      </ul>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col">
      <input [disabled]="!createForm.valid" class="btn btn-primary" type="submit" value="Submit">
    </div>
  </div>
</form>

// frontend-react/src/components/create-lightning-talk/create-lightning-talk.component.js
import { useState } from 'react';
import { useForm } from 'react-hook-form';

import './create-lightning-talk.component.css';
import LightningTalkService from '../../services/lightning-talk.service';

function CreateLightningTalk({ history }) {
  const [data, setData] = useState(null);

  // create lightning talk on form submit
  const onSubmit = (formData) => {
    LightningTalkService.create(formData.title, formData.description, formData.file[0]).then(res => {
      if (!res.data.error) {
        // redirect to the item just created if no errors
        history.push(`/lightning-talks/${res.data.result.id}`);
      } else {
        setData(res.data);
      }
    }).catch((error) => {
      if (error.response) {
        setData(error.response.data);
      }
    });
  };

  const { register, handleSubmit, errors } = useForm();

  return (
    <div>
      <h1 className="my-4 pt-4">Create Lightning Talk</h1>
      <form className="form-group" onSubmit={handleSubmit(onSubmit)}>
        <div className="row">
          <div className="col">
            <label htmlFor="title">Title
              { errors.title
                && <span className="text-danger">
                    <span>*</span>
                  </span>
              }
            </label>
            <input name="title" type="text" className="form-control" ref={register({required: true})} />
          </div>
        </div>
        <div className="row mt-3">
          <div className="col">
            <label htmlFor="description">Description
              { errors.description
                && <span className="text-danger">
                    <span>*</span>
                  </span>
              }
            </label>
            <textarea name="description" type="text" className="form-control" ref={register({required: true})}></textarea>
          </div>
        </div>
        <div className="row mt-3">
          <div className="col">
            <label htmlFor="file">PowerPoint
              { errors.file
                && <span className="text-danger">
                    <span>*</span>
                  </span>
              }
            </label>
            <input type="file" accept=".ppt,.pptx" name="file" className="form-control" ref={register({required: true})} />
          </div>
        </div>
        { (data && data.error)
          && <div className="row mt-3">
              <div className="col-12 alert alert-warning" role="alert">
                <ul className="mb-0">
                  { data.message.map((item, key) => (
                      <li key={key}>
                        <strong>{item}.</strong>
                      </li>
                    )) }
                </ul>
              </div>
            </div>
        }
        <div className="row mt-4">
          <div className="col">
            <input className="btn btn-primary" type="submit" value="Submit" />
          </div>
        </div>
      </form>
    </div>
  );
}

export default CreateLightningTalk;
