// frontend/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { first } from 'rxjs/operators';
import { AuthenticationService } from 'src/app/services/authentication.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  returnUrl: string;
  loginForm: FormGroup;
  apiResult;

  constructor(private formBuilder: FormBuilder, private route: ActivatedRoute, private router: Router, private authService: AuthenticationService) { }

  ngOnInit(): void {
    this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/';

    // redirect to home if already logged in
    if (this.authService.currentUserValue) {
      this.router.navigate(['/']);
    }

    this.loginForm = this.formBuilder.group({
      username: ['', Validators.required],
      password: [null, Validators.required]
    });
  }

  get controls() { return this.loginForm.controls; }

  login() {
    if (!this.loginForm.valid) {
      return;
    }

    this.authService.login(this.controls.username.value, this.controls.password.value)
      .pipe(first())
      .subscribe(data => {
        this.apiResult = data;
        if (!data.error) {
          this.router.navigate([this.returnUrl]);
        }
      }, error => {
        this.apiResult = error;
      });
  }
}

<h1 class="my-4 pt-4">Login</h1>
<form class="form-group" [formGroup]="loginForm" (ngSubmit)="login()">
  <div class="row">
    <div class="col">
      <label for="username">Username
        <span *ngIf="loginForm.controls['username'].invalid" class="text-danger">
          <span *ngIf="loginForm.controls['username'].errors.required">*</span>
        </span>
      </label>
      <input id="username" name="username" type="text" formControlName="username" class="form-control">
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <label for="password">Password
        <span *ngIf="loginForm.controls['password'].invalid" class="text-danger">
          <span *ngIf="loginForm.controls['password'].errors.required">*</span>
        </span>
      </label>
      <input id="password" name="password" type="password" formControlName="password" class="form-control">
    </div>
  </div>
  <div *ngIf="apiResult && apiResult.error" class="row mt-3">
    <div *ngFor="let msg of apiResult.message" class="col-12 alert alert-warning" role="alert">
      <strong>{{msg}}.</strong>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col">
      <input [disabled]="!loginForm.valid" class="btn btn-primary" type="submit" value="Login">
    </div>
  </div>
</form>

// frontend-react/src/components/login/login.component.js
import { useContext, useState } from 'react';
import { Link, Redirect } from 'react-router-dom';
import queryString from 'query-string';
import { useForm } from 'react-hook-form';

import './login.component.css';
import AuthService from '../../services/auth.service';
import { UserContext } from '../../contexts/user';

function Login({ location }) {
  const [data, setData] = useState(null);
  const [currentUser, setCurrentUser] = useContext(UserContext);
  const { register, handleSubmit, errors } = useForm();

  // Redirect out of here if user has already logged in
  if (currentUser) {
    const q = queryString.parse(location.search);
    return <Redirect to={q.returnUrl || '/'} />;
  }

  // Do login
  const onSubmit = (formData) => {
    AuthService.login(formData.username, formData.password).then(res => {
      if (!res.data.error) {
        setCurrentUser(res.data.result);
      } else {
        setData(res.data);
      }
    }).catch(error => {
      if (error.response) {
        setData(error.response.data);
      }
    });
  };

  return (
    <div>
      <h1 className="my-4 pt-4">Login</h1>
      <form className="form-group" onSubmit={handleSubmit(onSubmit)}>
        <div className="row">
          <div className="col">
            <label htmlFor="username">Username
              { errors.username
                && <span className="text-danger">
                    <span>*</span>
                  </span>
              }
            </label>
            <input name="username" type="text" className="form-control" ref={register({required: true})} />
          </div>
        </div>
        <div className="row mt-3">
          <div className="col">
            <label htmlFor="password">Password
              { errors.password
                && <span className="text-danger">
                    <span>*</span>
                  </span>
              }
            </label>
            <input name="password" type="password" className="form-control" ref={register({required: true})} />
          </div>
        </div>
        { (data && data.error)
          && <div className="row mt-3">
              <div className="col-12 alert alert-warning" role="alert">
                <ul className="mb-0">
                  { data.message.map((item, key) => (
                      <li key={key}>
                        <strong>{item}.</strong>
                      </li>
                    )) }
                </ul>
              </div>
            </div>
        }
        <div className="row mt-4">
          <div className="col">
            <input className="btn btn-primary mr-3" type="submit" value="Login" />/<Link to="/register" className="btn btn-link btn-sm ml-2">Register new user</Link>
          </div>
        </div>
      </form>
    </div>
  );
}

export default Login;
