// frontend/src/app/components/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  returnUrl: string;
  registerForm: FormGroup;
  apiResult;

  constructor(private formBuilder: FormBuilder,
    private router: Router,
    private userService: UserService) { }

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      username: ['', Validators.required],
      password: [null, Validators.required]
    });
  }

  get controls() { return this.registerForm.controls; }

  register() {
    if (!this.registerForm.valid) {
      return;
    }

    this.userService.register(this.controls.username.value, this.controls.password.value)
      .subscribe((data: any) => {
        if (data.error) {
          this.apiResult = data;
        } else {
          this.router.navigate(['login']);
        }
      }, error => {
        this.apiResult = error;
      });
  }
}

<h1 class="my-4 pt-4">Register</h1>
<form class="form-group" [formGroup]="registerForm" (ngSubmit)="register()">
  <div class="row">
    <div class="col">
      <label for="username">Username
        <span *ngIf="registerForm.controls['username'].invalid" class="text-danger">
          <span *ngIf="registerForm.controls['username'].errors.required">*</span>
        </span>
      </label>
      <input id="username" name="username" type="text" formControlName="username" class="form-control">
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <label for="password">Password
        <span *ngIf="registerForm.controls['password'].invalid" class="text-danger">
          <span *ngIf="registerForm.controls['password'].errors.required">*</span>
        </span>
      </label>
      <input id="password" name="password" type="password" formControlName="password" class="form-control">
    </div>
  </div>
  <div *ngIf="apiResult && apiResult.error" class="row mt-3">
    <div *ngFor="let msg of apiResult.message" class="col-12 alert alert-warning" role="alert">
      <strong>{{msg}}.</strong>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col">
      <input [disabled]="!registerForm.valid" class="btn btn-primary" type="submit" value="Register">
    </div>
  </div>
</form>

// frontend-react/src/components/register/register.component.js
import { useState } from 'react';
import { useForm } from 'react-hook-form';

import './register.component.css';
import AuthService from '../../services/auth.service';

function Register({ history }) {
  // Need the return url
  const [data, setData] = useState(null);

  // Do login
  const onSubmit = (formData) => {
    AuthService.register(formData.username, formData.password).then(res => {
      if (!res.data.error) {
        // Go to login page when register successful
        history.push('/login');
      } else {
        setData(res.data);
      }
    }).catch(error => {
      if (error.response) {
        setData(error.response.data);
      }
    });
  };

  const { register, handleSubmit, errors } = useForm();

  return (
    <div>
      <h1 className="my-4 pt-4">Register</h1>
      <form className="form-group" onSubmit={handleSubmit(onSubmit)}>
        <div className="row">
          <div className="col">
            <label htmlFor="username">Username
              { errors.username
                && <span className="text-danger">
                    <span>*</span>
                  </span>
              }
            </label>
            <input name="username" type="text" className="form-control" ref={register({required: true})} />
          </div>
        </div>
        <div className="row mt-3">
          <div className="col">
            <label htmlFor="password">Password
              { errors.password
                && <span className="text-danger">
                    <span>*</span>
                  </span>
              }
            </label>
            <input name="password" type="password" className="form-control" ref={register({required: true})} />
          </div>
        </div>
        { (data && data.error)
          && <div className="row mt-3">
              <div className="col-12 alert alert-warning" role="alert">
                <ul className="mb-0">
                  { data.message.map((item, key) => (
                      <li key={key}>
                        <strong>{item}.</strong>
                      </li>
                    )) }
                </ul>
              </div>
            </div>
        }
        <div className="row mt-4">
          <div className="col">
            <input className="btn btn-primary mr-3" type="submit" value="Register" />
          </div>
        </div>
      </form>
    </div>
  );
}

export default Register;
